### ISSUE TITLE
handleSubscription() implementaion is misleading

### ISSUE THREAD

**Issue by milen-yordanov** [stripe-samples/creating-subscriptions#15]
See: https://github.com/stripe-samples/set-up-subscriptions/blob/master/client/script.js#L97
```
    if (status === 'requires_action' || status === 'requires_payment_method') {
      stripe.confirmCardPayment(client_secret).then(function(result) {
      .....
```

If status === 'requires_payment_method' then stripe.confirmCardPayment() is called. But this is wrong. This case should be handled by changing the payment method. 

The docs at: https://stripe.com/docs/billing/subscriptions/payment say:
```
 if (status === "requires_action") {
    stripe.confirmCardSetup(client_secret).then(function(result) {
      if (result.error) {
        // Display error.message in your UI.
      } else {
        // The setup has succeeded. Display a success message.
      }
    });
  }
```

**Comment by lukeredpath** [comment]
This has been confusing me too. I tried this sample locally and couldn’t get it to work. confirmCardSetup doesn’t seem to know how to handle failed payment methods so I’m not sure why the example code does this. 

You can try this out using the hosted demo with test card 4000000000009995 which will be declined due to insufficient funds.

**Comment by ctrudeau-stripe** [comment]
Thanks for the write up. We've removed 'requires_payment_method' and will add in a future update handling payment failures like the one with the test card: 4000000000009995.
